"""
AI Analysis Progress Events.

Defines the standard event structure used by the
LangGraph AI analysis workflow.

These events are transport-independent.

Later they can be delivered through:

    LangGraph
        ↓
    ProgressPublisher
        ↓
    SSE / Redis / WebSocket
        ↓
    Frontend
"""

from enum import Enum

from pydantic import BaseModel, Field


# =============================================================================
# PROGRESS STATUS
# =============================================================================

class ProgressStatus(str, Enum):
    """
    Lifecycle status of an AI analysis task.
    """

    STARTED = "started"

    RUNNING = "running"

    COMPLETED = "completed"

    SKIPPED = "skipped"

    FAILED = "failed"


# =============================================================================
# PROGRESS EVENT
# =============================================================================

class ProgressEvent(BaseModel):
    """
    One progress event generated by the AI analysis workflow.

    Example:

        {
            "request_id": "REQ-123",
            "error_id": "ERR-001",
            "task_id": "rag_retrieval",
            "task_name": "RAG Retrieval",
            "status": "running",
            "progress": 35,
            "message": "Searching historical knowledge",
            "log_type": "laravel",
            "metadata": {}
        }
    """

    # -------------------------------------------------------------------------
    # REQUEST
    # -------------------------------------------------------------------------

    request_id: str = Field(
        description="Unique ID for the complete AI analysis request.",
    )

    # -------------------------------------------------------------------------
    # ERROR
    # -------------------------------------------------------------------------

    error_id: str | None = Field(
        default=None,
        description="ID of the error currently being processed.",
    )

    error_index: int | None = Field(
        default=None,
        description="Zero-based index of the current error.",
    )

    total_errors: int | None = Field(
        default=None,
        description="Total number of errors in the request.",
    )

    # -------------------------------------------------------------------------
    # TASK
    # -------------------------------------------------------------------------

    task_id: str = Field(
        description="Stable machine-readable task identifier.",
    )

    task_name: str = Field(
        description="Human-readable task name.",
    )

    # -------------------------------------------------------------------------
    # STATUS
    # -------------------------------------------------------------------------

    status: ProgressStatus = Field(
        description="Current lifecycle status of the task.",
    )

    # -------------------------------------------------------------------------
    # PROGRESS
    # -------------------------------------------------------------------------

    progress: int = Field(
        ge=0,
        le=100,
        description="Overall analysis progress from 0 to 100.",
    )

    # -------------------------------------------------------------------------
    # MESSAGE
    # -------------------------------------------------------------------------

    message: str = Field(
        description="Human-readable progress message.",
    )

    # -------------------------------------------------------------------------
    # LOG TYPE
    # -------------------------------------------------------------------------

    log_type: str | None = Field(
        default=None,
        description="Log type currently being analyzed.",
    )

    # -------------------------------------------------------------------------
    # METADATA
    # -------------------------------------------------------------------------

    metadata: dict = Field(
        default_factory=dict,
        description="Additional event-specific information.",
    )