"""
STEP 3.13.7 - PROGRESS EVENT COLLECTION TEST

Purpose:
    Verify that LangGraph correctly collects progress events
    generated by workflow nodes into:

        state["progress_events"]

This test focuses on event collection, not LLM correctness.
"""

import asyncio

from app.ai.graph.workflow import build_ai_analysis_graph


# =============================================================================
# TEST ERROR
# =============================================================================

TEST_ERROR = {
    "error_id": "TEST-3.13.7-001",
    "tier": "web",
    "log_type": "laravel",
    "server": "test-server",
    "file_name": "laravel.log",
    "file_path": "/var/log/laravel.log",
    "title": "Route not found",
    "severity": "ERROR",
    "timestamp": "2026-08-13T12:00:00",
    "start_line": 100,
    "end_line": 103,
    "total_lines": 4,
    "error_content": (
        "Route [dashboard] not defined."
    ),
    "lines": [
        {
            "line_number": 100,
            "content": (
                "production.ERROR: "
                "Route [dashboard] not defined."
            ),
        },
        {
            "line_number": 101,
            "content": (
                "at resources/views/layout.blade.php"
            ),
        },
        {
            "line_number": 102,
            "content": (
                "Route::route('dashboard')"
            ),
        },
        {
            "line_number": 103,
            "content": (
                "Stack trace available."
            ),
        },
    ],
}


# =============================================================================
# MAIN
# =============================================================================


async def main():

    print("=" * 100)
    print("STEP 3.13.7 - PROGRESS EVENT COLLECTION TEST")
    print("=" * 100)

    # -------------------------------------------------------------------------
    # Build graph
    # -------------------------------------------------------------------------

    print()
    print("Building LangGraph...")

    graph = build_ai_analysis_graph()

    print("Graph created: OK")

    # -------------------------------------------------------------------------
    # Initial state
    # -------------------------------------------------------------------------

    initial_state = {
        "request_id": "TEST-3.13.7",

        "tier": "web",

        "log_type": "laravel",

        "selected_errors": [
            TEST_ERROR,
        ],

        "current_error_index": 0,

        "current_error": None,

        "final_results": [],

        "progress_events": [],

        "messages": [],

        "status": "initialized",

        "progress": 0,
    }

    # -------------------------------------------------------------------------
    # Invoke graph
    # -------------------------------------------------------------------------

    print()
    print("Starting LangGraph...")
    print()

    try:

        result = await graph.ainvoke(
            initial_state
        )

    except Exception as exc:

        print()
        print("=" * 100)
        print("STEP 3.13.7 TEST FAILED")
        print("=" * 100)

        print(
            f"{type(exc).__name__}: {exc}"
        )

        raise

    # -------------------------------------------------------------------------
    # Extract events
    # -------------------------------------------------------------------------

    events = result.get(
        "progress_events",
        [],
    )

    print()
    print("=" * 100)
    print("PROGRESS EVENT COLLECTION")
    print("=" * 100)

    print(
        f"Total Events : {len(events)}"
    )

    # -------------------------------------------------------------------------
    # Basic validation
    # -------------------------------------------------------------------------

    if not events:

        raise AssertionError(
            "No progress events were collected."
        )

    # -------------------------------------------------------------------------
    # Print events
    # -------------------------------------------------------------------------

    print()

    for index, event in enumerate(events):

        print(
            f"[{index}] "
            f"{event.task_id} | "
            f"{event.status.value} | "
            f"{event.progress}% | "
            f"{event.message}"
        )

    # -------------------------------------------------------------------------
    # Validate event types
    # -------------------------------------------------------------------------

    for event in events:

        if event.request_id != "TEST-3.13.7":

            raise AssertionError(
                "Incorrect request_id in "
                f"event: {event}"
            )

    # -------------------------------------------------------------------------
    # Validate progress range
    # -------------------------------------------------------------------------

    for event in events:

        if not 0 <= event.progress <= 100:

            raise AssertionError(
                "Invalid progress value: "
                f"{event.progress}"
            )

    # -------------------------------------------------------------------------
    # Validate final event
    # -------------------------------------------------------------------------

    final_event = events[-1]

    print()
    print(
        f"Final Event : "
        f"{final_event.task_id}"
    )

    print(
        f"Final Status: "
        f"{final_event.status.value}"
    )

    print(
        f"Final Progress: "
        f"{final_event.progress}%"
    )

    if final_event.progress != 100:

        raise AssertionError(
            "Final progress event is not 100%."
        )

    # -------------------------------------------------------------------------
    # Validate finalization
    # -------------------------------------------------------------------------

    if final_event.task_id != "finalize_analysis":

        raise AssertionError(
            "Final event is not "
            "finalize_analysis."
        )

    # -------------------------------------------------------------------------
    # Validate state progress
    # -------------------------------------------------------------------------

    final_progress = result.get(
        "progress"
    )

    print()
    print(
        f"Final State Progress : "
        f"{final_progress}"
    )

    if final_progress != 100:

        raise AssertionError(
            "Final state progress is not 100."
        )

    # -------------------------------------------------------------------------
    # Validate final status
    # -------------------------------------------------------------------------

    final_status = result.get(
        "status"
    )

    print(
        f"Final State Status   : "
        f"{final_status}"
    )

    # -------------------------------------------------------------------------
    # SUCCESS
    # -------------------------------------------------------------------------

    print()
    print("=" * 100)
    print("STEP 3.13.7 TEST PASSED")
    print("=" * 100)

    print(
        f"Collected Events : {len(events)}"
    )

    print(
        "Progress Event History : OK"
    )

    print(
        "Final Progress         : 100%"
    )

    print(
        "Finalization Event     : OK"
    )

    print("=" * 100)


if __name__ == "__main__":

    asyncio.run(main())